create or replace
PACKAGE DEBITORS_PACK AS 

APPEND_TASKS CONSTANT BOOLEAN := FALSE; -- <-- TRUE davalebebis generaciisTvis
MISSHOLIDAYS_FROM_SYSDATE CONSTANT BOOLEAN := FALSE;

TYPE_CHARGE  CONSTANT NUMBER := 1;
TYPE_PAYMNET CONSTANT NUMBER := 2;
TYPE_VOUCHER CONSTANT NUMBER := 3;
TYPE_PORTION CONSTANT NUMBER := 4;
TYPE_SUBSIDY CONSTANT NUMBER := 5;

STAT_PAY_VIOLATION CONSTANT NUMBER := 1;
STAT_BALANCE_GE_50 CONSTANT NUMBER := 8;
STAT_SCHEDULE_VIOLATION CONSTANT NUMBER := 14;
STAT_BALANCE_GE_5000 CONSTANT NUMBER := 15;
STAT_DEBT_TOO_OLD CONSTANT NUMBER := 16;
STAT_DEBT_OLDNESS_1M CONSTANT NUMBER := 17;
STAT_DEBT_OLDNESS_2M CONSTANT NUMBER := 18;
STAT_DEBT_OLDNESS_3M CONSTANT NUMBER := 18;
STAT_LARGE_CONSUMER CONSTANT NUMBER := 27;

LIMIT_OLDNESS CONSTANT NUMBER := 1095; -- days

PROCEDURE fill_zdebitors;

END DEBITORS_PACK;